name: Build CrackLeaf Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build with Nuitka
        run: |
          nuitka main.py --standalone --enable-plugin=tk-inter --output-dir=dist --nofollow-import-to=*.tests --assume-yes-for-downloads --onefile --output-filename=CrackLeaf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CrackLeaf-${{ matrix.os }}
          path: dist/CrackLeaf*
